/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package book.management.components;

import book.management.models.Book;
import book.management.models.Category;
import book.management.models.Publisher;
import book.management.repository.BookRepository;
import book.management.repository.CategoryRepository;
import book.management.repository.PublisherRepository;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

public class App extends javax.swing.JFrame {

    private BookRepository bookRepo;
    private CategoryRepository cateRepo;
    private PublisherRepository publisherRepo;

    private List<String> categories = new ArrayList<>();
    private Map<String, Integer> mapCategories = new HashMap<>();

    private List<String> publishers = new ArrayList<>();
    private Map<String, Integer> mapPublishers = new HashMap<>();

    private int idUpdate;

    /**
     * Creates new form App
     */
    public App() {
        bookRepo = new BookRepository();
        cateRepo = new CategoryRepository();
        publisherRepo = new PublisherRepository();

        initComponents();
        this.updatePanel.setVisible(false);
        this.addPanel.setVisible(false);
        initSelection();
    }

    private void initSelection() {
        List<Category> cateVals = cateRepo.listAll();
        for (Category c : cateVals) {
            this.categories.add(c.getName());
            this.mapCategories.put(c.getName(), c.getId());
        }

        List<Publisher> pubVals = publisherRepo.listAll();
        for (Publisher p : pubVals) {
            this.publishers.add(p.getName());
            this.mapPublishers.put(p.getName(), p.getId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        searchTf = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        addNewBtn = new javax.swing.JButton();
        bodyPanel = new javax.swing.JPanel();
        tblScroll = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        updatePanel = new javax.swing.JPanel();
        nameLinePanel = new javax.swing.JPanel();
        nameUpdateLabel = new javax.swing.JLabel();
        nameUpdateTf = new javax.swing.JTextField();
        authorLinePanel = new javax.swing.JPanel();
        authorUpdateLabel = new javax.swing.JLabel();
        authorUpdateTf = new javax.swing.JTextField();
        priceLinePanel = new javax.swing.JPanel();
        priceUpdateLabel = new javax.swing.JLabel();
        priceUpdateTf = new javax.swing.JTextField();
        qtyLinePanel = new javax.swing.JPanel();
        qtyUpdateLabel = new javax.swing.JLabel();
        qtyUpdateTf = new javax.swing.JTextField();
        categoryLinePanel = new javax.swing.JPanel();
        categoryUpdateLabel = new javax.swing.JLabel();
        categoryUpdateCb = new javax.swing.JComboBox<>();
        publisherLinePanel = new javax.swing.JPanel();
        publisherUpdateLabel = new javax.swing.JLabel();
        publisherUpdateCb = new javax.swing.JComboBox<>();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        addPanel = new javax.swing.JPanel();
        nameAddLinePanel = new javax.swing.JPanel();
        nameAddLabel = new javax.swing.JLabel();
        nameAddTf = new javax.swing.JTextField();
        authorAddLinePanel = new javax.swing.JPanel();
        authorAddLabel = new javax.swing.JLabel();
        authorAddTf = new javax.swing.JTextField();
        priceAddLinePanel = new javax.swing.JPanel();
        priceAddLabel = new javax.swing.JLabel();
        priceAddTf = new javax.swing.JTextField();
        qtyAddLinePanel = new javax.swing.JPanel();
        qtyAddLabel = new javax.swing.JLabel();
        qtyAddTf = new javax.swing.JTextField();
        categoryAddLinePanel = new javax.swing.JPanel();
        categoryAddLabel = new javax.swing.JLabel();
        categoryAddCb = new javax.swing.JComboBox<>();
        publisherAddLinePanel = new javax.swing.JPanel();
        publisherAddLabel = new javax.swing.JLabel();
        publisherAddCb = new javax.swing.JComboBox<>();
        cancelAddBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        searchTf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        searchBtn.setText("Search");
        searchBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchBtn.setSize(new java.awt.Dimension(90, 23));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        addNewBtn.setText("Add");
        addNewBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addNewBtn.setSize(new java.awt.Dimension(90, 23));
        addNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchTf, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addNewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(addNewBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchTf))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Name", "Author", "Price", "Qty", "Category", "Publisher", "Received Time", "Modified Time"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        tblScroll.setViewportView(tbl);
        if (tbl.getColumnModel().getColumnCount() > 0) {
            tbl.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        updatePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nameLinePanel.setPreferredSize(new java.awt.Dimension(175, 50));

        nameUpdateLabel.setText("Name");

        javax.swing.GroupLayout nameLinePanelLayout = new javax.swing.GroupLayout(nameLinePanel);
        nameLinePanel.setLayout(nameLinePanelLayout);
        nameLinePanelLayout.setHorizontalGroup(
            nameLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameUpdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameUpdateTf)
                .addContainerGap())
        );
        nameLinePanelLayout.setVerticalGroup(
            nameLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nameLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nameLinePanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(nameUpdateTf, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addComponent(nameUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        authorLinePanel.setPreferredSize(new java.awt.Dimension(175, 50));

        authorUpdateLabel.setText("Author");

        javax.swing.GroupLayout authorLinePanelLayout = new javax.swing.GroupLayout(authorLinePanel);
        authorLinePanel.setLayout(authorLinePanelLayout);
        authorLinePanelLayout.setHorizontalGroup(
            authorLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authorLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(authorUpdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorUpdateTf)
                .addContainerGap())
        );
        authorLinePanelLayout.setVerticalGroup(
            authorLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authorLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(authorLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(authorLinePanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(authorUpdateTf, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addComponent(authorUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        priceLinePanel.setPreferredSize(new java.awt.Dimension(175, 50));

        priceUpdateLabel.setText("Price");

        javax.swing.GroupLayout priceLinePanelLayout = new javax.swing.GroupLayout(priceLinePanel);
        priceLinePanel.setLayout(priceLinePanelLayout);
        priceLinePanelLayout.setHorizontalGroup(
            priceLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(priceLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(priceUpdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceUpdateTf)
                .addContainerGap())
        );
        priceLinePanelLayout.setVerticalGroup(
            priceLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(priceLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(priceLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(priceLinePanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(priceUpdateTf, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addComponent(priceUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        qtyLinePanel.setPreferredSize(new java.awt.Dimension(175, 50));

        qtyUpdateLabel.setText("Quantity");

        javax.swing.GroupLayout qtyLinePanelLayout = new javax.swing.GroupLayout(qtyLinePanel);
        qtyLinePanel.setLayout(qtyLinePanelLayout);
        qtyLinePanelLayout.setHorizontalGroup(
            qtyLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qtyLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(qtyUpdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtyUpdateTf)
                .addContainerGap())
        );
        qtyLinePanelLayout.setVerticalGroup(
            qtyLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qtyLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(qtyLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qtyLinePanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(qtyUpdateTf, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addComponent(qtyUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        categoryLinePanel.setPreferredSize(new java.awt.Dimension(175, 50));

        categoryUpdateLabel.setText("Category");

        categoryUpdateCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout categoryLinePanelLayout = new javax.swing.GroupLayout(categoryLinePanel);
        categoryLinePanel.setLayout(categoryLinePanelLayout);
        categoryLinePanelLayout.setHorizontalGroup(
            categoryLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(categoryUpdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryUpdateCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        categoryLinePanelLayout.setVerticalGroup(
            categoryLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(categoryLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryUpdateCb, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(categoryUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        publisherLinePanel.setPreferredSize(new java.awt.Dimension(175, 50));

        publisherUpdateLabel.setText("Publisher");

        publisherUpdateCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout publisherLinePanelLayout = new javax.swing.GroupLayout(publisherLinePanel);
        publisherLinePanel.setLayout(publisherLinePanelLayout);
        publisherLinePanelLayout.setHorizontalGroup(
            publisherLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publisherLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(publisherUpdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(publisherUpdateCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        publisherLinePanelLayout.setVerticalGroup(
            publisherLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publisherLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(publisherLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(publisherUpdateCb, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(publisherUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        deleteBtn.setText("Remove");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLinePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(authorLinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(priceLinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(qtyLinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(categoryLinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(publisherLinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addGap(0, 70, Short.MAX_VALUE)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(nameLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtyLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(publisherLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        addPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nameAddLinePanel.setPreferredSize(new java.awt.Dimension(175, 50));

        nameAddLabel.setText("Name");

        javax.swing.GroupLayout nameAddLinePanelLayout = new javax.swing.GroupLayout(nameAddLinePanel);
        nameAddLinePanel.setLayout(nameAddLinePanelLayout);
        nameAddLinePanelLayout.setHorizontalGroup(
            nameAddLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameAddLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameAddTf)
                .addContainerGap())
        );
        nameAddLinePanelLayout.setVerticalGroup(
            nameAddLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameAddLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nameAddLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nameAddLinePanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(nameAddTf, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addComponent(nameAddLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        authorAddLinePanel.setPreferredSize(new java.awt.Dimension(175, 50));

        authorAddLabel.setText("Author");

        javax.swing.GroupLayout authorAddLinePanelLayout = new javax.swing.GroupLayout(authorAddLinePanel);
        authorAddLinePanel.setLayout(authorAddLinePanelLayout);
        authorAddLinePanelLayout.setHorizontalGroup(
            authorAddLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authorAddLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(authorAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorAddTf)
                .addContainerGap())
        );
        authorAddLinePanelLayout.setVerticalGroup(
            authorAddLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authorAddLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(authorAddLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(authorAddLinePanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(authorAddTf, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addComponent(authorAddLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        priceAddLinePanel.setPreferredSize(new java.awt.Dimension(175, 50));

        priceAddLabel.setText("Price");

        javax.swing.GroupLayout priceAddLinePanelLayout = new javax.swing.GroupLayout(priceAddLinePanel);
        priceAddLinePanel.setLayout(priceAddLinePanelLayout);
        priceAddLinePanelLayout.setHorizontalGroup(
            priceAddLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(priceAddLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(priceAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceAddTf)
                .addContainerGap())
        );
        priceAddLinePanelLayout.setVerticalGroup(
            priceAddLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(priceAddLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(priceAddLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(priceAddLinePanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(priceAddTf, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addComponent(priceAddLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        qtyAddLinePanel.setPreferredSize(new java.awt.Dimension(175, 50));

        qtyAddLabel.setText("Quantity");

        javax.swing.GroupLayout qtyAddLinePanelLayout = new javax.swing.GroupLayout(qtyAddLinePanel);
        qtyAddLinePanel.setLayout(qtyAddLinePanelLayout);
        qtyAddLinePanelLayout.setHorizontalGroup(
            qtyAddLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qtyAddLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(qtyAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtyAddTf)
                .addContainerGap())
        );
        qtyAddLinePanelLayout.setVerticalGroup(
            qtyAddLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qtyAddLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(qtyAddLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qtyAddLinePanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(qtyAddTf, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addComponent(qtyAddLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        categoryAddLinePanel.setPreferredSize(new java.awt.Dimension(175, 50));

        categoryAddLabel.setText("Category");

        categoryAddCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout categoryAddLinePanelLayout = new javax.swing.GroupLayout(categoryAddLinePanel);
        categoryAddLinePanel.setLayout(categoryAddLinePanelLayout);
        categoryAddLinePanelLayout.setHorizontalGroup(
            categoryAddLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryAddLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(categoryAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryAddCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        categoryAddLinePanelLayout.setVerticalGroup(
            categoryAddLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryAddLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(categoryAddLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryAddCb, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(categoryAddLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        publisherAddLinePanel.setPreferredSize(new java.awt.Dimension(175, 50));

        publisherAddLabel.setText("Publisher");

        publisherAddCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout publisherAddLinePanelLayout = new javax.swing.GroupLayout(publisherAddLinePanel);
        publisherAddLinePanel.setLayout(publisherAddLinePanelLayout);
        publisherAddLinePanelLayout.setHorizontalGroup(
            publisherAddLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publisherAddLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(publisherAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(publisherAddCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        publisherAddLinePanelLayout.setVerticalGroup(
            publisherAddLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publisherAddLinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(publisherAddLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(publisherAddCb, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(publisherAddLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        cancelAddBtn.setText("Cancel");
        cancelAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddBtnActionPerformed(evt);
            }
        });

        addBtn.setText("Add New");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameAddLinePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(authorAddLinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(priceAddLinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(qtyAddLinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(categoryAddLinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(publisherAddLinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(0, 70, Short.MAX_VALUE)
                        .addComponent(cancelAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameAddLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorAddLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceAddLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtyAddLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryAddLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(publisherAddLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblScroll)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(updatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listAllBook() {
        List<Book> books;
        String search = searchTf.getText();
        if (search.isEmpty()) {
            books = bookRepo.listProduct();
        } else {
            books = bookRepo.searchBook(search);
        }
        renderTable(books);
    }

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        listAllBook();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int id = idUpdate;
        bookRepo.removeBook(id);
        listAllBook();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        this.updatePanel.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        int row = tbl.getSelectedRow();
        idUpdate = Integer.parseInt(model.getValueAt(row, 0).toString());
        nameUpdateTf.setText(model.getValueAt(row, 1).toString());
        authorUpdateTf.setText(model.getValueAt(row, 2).toString());
        priceUpdateTf.setText(model.getValueAt(row, 3).toString());
        qtyUpdateTf.setText(model.getValueAt(row, 4).toString());

        String selectedCategory = model.getValueAt(row, 5).toString();
        DefaultComboBoxModel cateComboBoxModel = new DefaultComboBoxModel(this.categories.toArray());
        categoryUpdateCb.setModel(cateComboBoxModel);
        categoryUpdateCb.setSelectedItem(selectedCategory);

        String selectedPublisher = model.getValueAt(row, 6).toString();
        DefaultComboBoxModel pubComboBoxModel = new DefaultComboBoxModel(this.publishers.toArray());
        publisherUpdateCb.setModel(pubComboBoxModel);
        publisherUpdateCb.setSelectedItem(selectedPublisher);
    }//GEN-LAST:event_tblMouseClicked

    private void addNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBtnActionPerformed
        DefaultComboBoxModel cateComboBoxModel = new DefaultComboBoxModel(this.categories.toArray());
        categoryAddCb.setModel(cateComboBoxModel);
        DefaultComboBoxModel pubComboBoxModel = new DefaultComboBoxModel(this.publishers.toArray());
        publisherAddCb.setModel(pubComboBoxModel);
        
        this.addPanel.setVisible(true);
    }//GEN-LAST:event_addNewBtnActionPerformed

    private void cancelAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddBtnActionPerformed
        this.listAllBook();
        this.updatePanel.setVisible(true);
    }//GEN-LAST:event_cancelAddBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        int id = idUpdate;
        String name = nameUpdateTf.getText();
        String author = authorUpdateTf.getText();
        int price = Integer.parseInt(priceUpdateTf.getText());
        int qty = Integer.parseInt(qtyUpdateTf.getText());
        int categoryId = mapCategories.get(categoryUpdateCb.getSelectedItem().toString());
        int publisherId = mapPublishers.get(publisherUpdateCb.getSelectedItem().toString());
        Book b = new Book(id, name, author, price, qty, categoryId, publisherId);
        bookRepo.updateBook(b);
        listAllBook();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String name = nameAddTf.getText();
        String author = authorAddTf.getText();
        int price = Integer.parseInt(priceAddTf.getText());
        int qty = Integer.parseInt(qtyAddTf.getText());
        int categoryId = mapCategories.get(categoryAddCb.getSelectedItem().toString());
        int publisherId = mapPublishers.get(publisherAddCb.getSelectedItem().toString());
        Book b = new Book(0, name, author, price, qty, categoryId, publisherId);
        bookRepo.createBook(b);
        listAllBook();
    }//GEN-LAST:event_addBtnActionPerformed

    private void renderTable(List<Book> books) {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0);
        for (Book book : books) {
            model.addRow(new Object[]{
                book.getId(),
                book.getName(),
                book.getAuthor(),
                book.getPrice(),
                book.getQty(),
                book.getCategoryName(),
                book.getPublisherName(),
                book.getCreatedAt(),
                book.getUpdatedAt()
            });
        }
        bodyPanel.revalidate();
        bodyPanel.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addNewBtn;
    private javax.swing.JPanel addPanel;
    private javax.swing.JLabel authorAddLabel;
    private javax.swing.JPanel authorAddLinePanel;
    private javax.swing.JTextField authorAddTf;
    private javax.swing.JPanel authorLinePanel;
    private javax.swing.JLabel authorUpdateLabel;
    private javax.swing.JTextField authorUpdateTf;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton cancelAddBtn;
    private javax.swing.JComboBox<String> categoryAddCb;
    private javax.swing.JLabel categoryAddLabel;
    private javax.swing.JPanel categoryAddLinePanel;
    private javax.swing.JPanel categoryLinePanel;
    private javax.swing.JComboBox<String> categoryUpdateCb;
    private javax.swing.JLabel categoryUpdateLabel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel nameAddLabel;
    private javax.swing.JPanel nameAddLinePanel;
    private javax.swing.JTextField nameAddTf;
    private javax.swing.JPanel nameLinePanel;
    private javax.swing.JLabel nameUpdateLabel;
    private javax.swing.JTextField nameUpdateTf;
    private javax.swing.JLabel priceAddLabel;
    private javax.swing.JPanel priceAddLinePanel;
    private javax.swing.JTextField priceAddTf;
    private javax.swing.JPanel priceLinePanel;
    private javax.swing.JLabel priceUpdateLabel;
    private javax.swing.JTextField priceUpdateTf;
    private javax.swing.JComboBox<String> publisherAddCb;
    private javax.swing.JLabel publisherAddLabel;
    private javax.swing.JPanel publisherAddLinePanel;
    private javax.swing.JPanel publisherLinePanel;
    private javax.swing.JComboBox<String> publisherUpdateCb;
    private javax.swing.JLabel publisherUpdateLabel;
    private javax.swing.JLabel qtyAddLabel;
    private javax.swing.JPanel qtyAddLinePanel;
    private javax.swing.JTextField qtyAddTf;
    private javax.swing.JPanel qtyLinePanel;
    private javax.swing.JLabel qtyUpdateLabel;
    private javax.swing.JTextField qtyUpdateTf;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTf;
    private javax.swing.JTable tbl;
    private javax.swing.JScrollPane tblScroll;
    private javax.swing.JButton updateBtn;
    private javax.swing.JPanel updatePanel;
    // End of variables declaration//GEN-END:variables
}
